language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
    - master
    - release

install:
  - pip install -r requirements-dev.txt
  - pip install codecov

script: scripts/test.sh

after_success:
  - codecov

jobs:
  include:
    - stage: deploy
      python: 3.8
      install: pip install twine
      script:
        - if [[ "$TRAVIS_BRANCH" == "release" && "$TRAVIS_PULL_REQUEST" = "false" ]];then chmod +x scripts/deploy.sh; ./scripts/deploy.sh; fi
