language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - CODECOV_TOKEN=CODECOV_KEY


install:
  - pip install -r requirements-dev.txt
  - pip install coverage codecov

script:
  - pytest --cov-report term --cov=tests/

after_success:
  - codecov
