language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
    - master
    - stable

install:
  - pip install -r requirements-dev.txt
  - pip install codecov

script: scripts/test.sh

after_success:
  - codecov

jobs:
  include:
    - stage: deploy
        python: "3.8"
        install: pip install twine

        deploy:
          provider: script
          script:
            - if [[ $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "stable" ]] ; then ./scripts/deploy.sh ; fi
          on:
            branch: stable
