language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
    - master
    - stable

install:
  - pip install -r requirements-dev.txt
  - pip install codecov twine

script:
  - pytest --cov-report term --cov

after_success:
  - codecov

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: stable
