site_name: Yaat
site_description: Yet another ASGI toolkit.

theme:
    name: 'material'

extra_css:
    - 'stylesheets/extra.css'

repo_name: yaat-project/yaat
repo_url: https://github.com/yaat-project/yaat

nav:
    - Introduction: index.md
    - Requests: requests.md
    - Responses: responses.md
    - Routing: routing.md
    - WebSockets: websockets.md
    - Static Files: staticfiles.md
    - Templates: templates.md
    - Background Tasks: backgroundtasks.md
    - Test Client: testclient.md
    - Third Party Libraries: thirdparty.md
    - Release Notes: releasenotes.md
